apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
spec:
  selector:
    matchLabels:
      name: load-test
  replicas: 1
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: gcr.io/pl-dev-infra/demos/microservice-kafka/load-test:3.0
        command: ["locust"]
        args: ["-u", "1", "-r", "1", "--headless", "-f", "/config/locustfile.py",
               "--host", "http://apache.default.svc.cluster.local:8080"]