version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
  apache:
    build: ../src/apache
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  postgres:
    build: ../src/postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
  order:
    build: ../src/microservice-kafka-order
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  shipping:
    build: ../src/microservice-kafka-shipping
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  invoicing:
    build: ../src/microservice-kafka-invoicing
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  load-test:
    build: ../src/microservice-kafka-load-test
    links:
     - apache

